version: 2

models:
  - name: customers
    description: "{{ doc('dim_customers') }}"
    columns:
      - name: customer_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: first_order_date
        description: NULL when a customer has not yet placed an order.

  - name: stg_customers
    description: This model cleans up customer data
    columns:
      - name: customer_id
        description: Primary key
        tests:
          - unique
          - not_null

  - name: stg_orders
    description: This model cleans up order data
    columns:
      - name: order_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']

  - name: stg_payments
    description: This model cleans up payment data
    columns:
    - name: payment_id
      description: Primary key
      tests:
        - unique
        - not_null
    - name: order_id
      description: Foreign key to orders
      tests:
        - relationships:
            to: ref('stg_orders')
            field: order_id
    - name: status
      tests:
        - accepted_values:
            values: ['success', 'fail']

  - name: orders
    description: One line per order
    columns:
    - name: order_id
      description: Primary key
      tests:
        - unique
        - not_null
    - name: customer_id
      description: Foreign Key to customers
      test:
        - relationships:
            to: ref('customers')
            field: customer_id
    - name: amount
      description: Order amount in USD
